# Generated by Django 4.1.1 on 2022-09-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kcmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbook',
            old_name='user',
            new_name='name',
        ),
    ]
