# Generated by Django 4.0.4 on 2022-09-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcmapp', '0003_alter_cashbook_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
