# Generated by Django 4.0.4 on 2022-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kcmapp', '0004_cashbook_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
